apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: commander
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: commander-legacy-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: wing
    app.kubernetes.io/part-of: wing
    app.kubernetes.io/managed-by: kustomize
  name: commander-legacy-metrics-service
  namespace: system
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    control-plane: commander
