# permissions for end users to edit replicaautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: replicaautoscaler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: wing
    app.kubernetes.io/part-of: wing
    app.kubernetes.io/managed-by: kustomize
  name: replicaautoscaler-editor-role
rules:
- apiGroups:
  - wing.xscaling.dev
  resources:
  - replicaautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wing.xscaling.dev
  resources:
  - replicaautoscalers/status
  verbs:
  - get
