apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kuberentes.io/instance: commander
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: wing
    app.kubernetes.io/part-of: wing
    app.kubernetes.io/managed-by: kustomize
  name: commander
  namespace: system
