workers: 3
plugins:
  cpu:
    utilizationToleration: 0.05
  memory:
    utilizationToleration: 0.05
  prometheus:
    toleration: 0.05
    defaultTimeout: 5s
    defaultServer:
      serverAddress: http://prometheus
  # using default config
  simple: {}
