// generated by generate_plugin_discovery.go; DO NOT EDIT

package plugin

import (
	// Include all plugins.
	_ "github.com/xscaling/wing/plugins/replicator_simple"
	_ "github.com/xscaling/wing/plugins/scaler_cpu"
	_ "github.com/xscaling/wing/plugins/scaler_memory"
	_ "github.com/xscaling/wing/plugins/scaler_prometheus"
)
